version: '3'

services:
  db:
    image: postgres:17.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comercio_db
    container_name: ol_container
    volumes:
      - ./postgres:/var/lib/postgresql/data
